name: ARMv8 OpenWrt

on:
  workflow_dispatch:
  schedule:
    - cron: 0 20 * * *
  
jobs:
  Build:
    runs-on: ubuntu-22.04
  
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization Environment
      run: |
        docker rmi $(docker images -q)
        sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android $AGENT_TOOLSDIRECTORY
        sudo -E apt-get -y update
        sudo -E apt-get -y install $(curl -fsSL is.gd/depends_ubuntu_2204)
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get -y clean

    - name: Download Armvirt Firmware
      id: download
      run: |
        wget https://github.com/oppen321/openwrt_packit/releases/download/Firmware_openwrt/openwrt-armsr-armv8-generic-rootfs.tar.gz

    - name: Package OpenWrt Firmware
      uses: unifreq/openwrt_packit@master
      env:
        OPENWRT_ARMVIRT: openwrt-armsr-armv8-generic-rootfs.tar.gz
        PACKAGE_SOC: all
        KERNEL_VERSION_NAME: 6.1.y_6.6.y

    - name: Upload OpenWrt Firmware to Release
      uses: ncipollo/release-action@main
      with:
        tag: openwrt_armvirt
        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
        allowUpdates: true
        token: ${{ secrets.GH_TOKEN }}
        body: |
          This is OpenWrt firmware for Armvirt 64
          * Firmware information
          Default IP: 10.0.0.1
          Default username: root
          Default password: password
